version: '3.8'

services:
  # 1. Database (PostgreSQL + PostGIS)
  db:
    image: scofield28/participium-team10:db-demo-3
    build: ./server/src/database
    container_name: participium_db
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Backend (Node.js API)
  server:
    image: scofield28/participium-team10:server-demo-3
    build: ./server
    container_name: participium_server
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
    environment:
      PORT: ${PORT}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      STORAGE_TYPE: local
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_ENABLED: ${TELEGRAM_BOT_ENABLED}
    depends_on:
      db:
        condition: service_healthy

  # 3. Frontend (Nginx + React)
  client:
    image: scofield28/participium-team10:client-demo-3
    build: ./client
    container_name: participium_client
    restart: unless-stopped
    ports:
      # Mappa la porta 80 del container (Nginx) sulla porta 80 del tuo PC
      - "80:80"
    depends_on:
      - server

volumes:
  postgres_data: